// Code generated by _http. DO NOT EDIT.

package example

import (
	"github.com/go-productive/_http"
	pkg1 "github.com/go-productive/_http/example/pkg1"
	"github.com/go-productive/_http/example/pkg2"
)

func (e *Example) RegisterRoute(server *_http.Server) {

	server.Engine.GET("/hello", server.GinHandlerFunc(func() interface{} { return new(pkg1.HelloRequest) },
		func(req interface{}, ctx interface{}) (interface{}, error) {
			return e.Hello(req.(*pkg1.HelloRequest), ctx.(*_http.DefaultContext))
		}))

	server.Engine.GET("/hi", server.GinHandlerFunc(func() interface{} { return new(pkg2.HelloResponse) },
		func(req interface{}, ctx interface{}) (interface{}, error) {
			return e.Hi(req.(*pkg2.HelloResponse), ctx.(*_http.DefaultContext))
		}))

}
